// import type { Metadata } from "next";
// import "./globals.css";
// import { Teachers } from "next/font/google";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import { AuroraBackground } from "@/components/ui/aurora-background";

// import { ClerkProvider } from "@clerk/nextjs";
// import { neobrutalism } from "@clerk/themes";

// export const metadata: Metadata = {
//   title: "Paper Analysis",
//   description: "Generated by create next app",
// };

// const teachers = Teachers({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800"],
//   style: ["normal", "italic"],
//   variable: "--font-teachers",
// });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <ClerkProvider
//       appearance={{
//         baseTheme: neobrutalism,
//       }}
//     >
//       <html lang="en">
//         <body className={teachers.className}>
//           <AuroraBackground>
//             <Navbar />
//             {children}
//             <Footer />
//           </AuroraBackground>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }

// app/layout.tsx
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { Teachers } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuroraBackground } from "@/components/ui/aurora-background";
import PageViewTracker from "@/components/PageViewTracker";

import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
import { GA_TRACKING_ID } from "@/lib/gtag";

export const metadata: Metadata = {
  title: "Paper Analysis - AI-Driven Exam Insights",
  description:
    "Analyze past exam papers to discover trends, common questions, and key topics with AI insights.",
  openGraph: {
    title: "Paper Analysis - AI Exam Insights",
    description:
      "AI-powered exam paper analysis to track common questions and optimize your exam preparation.",
    url: "https://www.paperanalysis.com",
    siteName: "Paper Analysis",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Paper Analysis - AI Exam Insights",
      },
    ],
    type: "website",
  },
};

const teachers = Teachers({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-teachers",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
      }}
    >
      <html lang="en">
        <head>
          {/* Google Analytics Scripts */}
          {GA_TRACKING_ID && (
            <>
              <Script
                strategy="afterInteractive"
                src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
              />
              <Script
                id="google-analytics"
                strategy="afterInteractive"
                dangerouslySetInnerHTML={{
                  __html: `
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', '${GA_TRACKING_ID}', {
                      page_path: window.location.pathname,
                    });
                  `,
                }}
              />
            </>
          )}
        </head>
        <body className={teachers.className}>
          <AuroraBackground>
            <Navbar />
            <PageViewTracker />
            {children}
            <Footer />
          </AuroraBackground>
        </body>
      </html>
    </ClerkProvider>
  );
}
