import type { Metadata } from "next";
import "./globals.css";
import { Teachers } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuroraBackground } from "@/components/ui/aurora-background";

import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Paper Analysis",
  description: "Generated by create next app",
};

const teachers = Teachers({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-teachers",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
      }}
    >
      <html lang="en">
        <body className={teachers.className}>
          <AuroraBackground>
            <Navbar />
            {children}
            <Footer />
          </AuroraBackground>
        </body>
      </html>
    </ClerkProvider>
  );
}
